### ISSUE TITLE
Remove Useless package.

### ISSUE THREAD

**Issue by shirshak55** [gumbo-millennium/website#82]
Before adding package I think it is necessary to read some source code etc. 

madewithlove/laravel-nova-uuid-support

This package is completely useless and provides no benefit.

Its service provider just registers database and does nothing. I was amazed to see this project using it :P

**Comment by roelofr** [comment]
Ehh, it's actually critical.

The service provider registers [one migration][1] that changes the `action_events` of Laravel Nova to use strings instead of integers, since we're using UUIDs for our enrollments.

Without this package, we can't unenroll or transfer enrollments on activities.

[1]: https://github.com/madewithlove/laravel-nova-uuid-support/blob/master/database/migrations/2019_11_21_000000_change_action_event_ids_to_strings.php

**Comment by shirshak55** [comment]
@roelofr actually what we should do instead of using package , publish the migration from laravel nova and change it . Remember service provider are loaded on every request meaning u are running useless code on hot path. And composer install etc also takes time. There are microoptimization which may not be necessary but as package and dependencies grows it does matter a lot :)

**Comment by roelofr** [comment]
Okay, you bring a fair point.

There's a challenge though, since we've already gone live. How would you reckon we handle the change in migrations (when we publish them) to prevent Laravel going paws up when we roll out this change.

Do feel free to make a PR out of this though, you'd be the first and it would really help.

I'm currently very cramped up with time (yeah, didn't expect it either in these quarantine times), so if you could handle this issue that would be awesome :tada:

**Comment by shirshak55** [comment]
Solved with #84

**Comment by shirshak55** [comment]
I think we can close :)

**Comment by roelofr** [comment]
Fixed in #84, which is merged using commit 1,000 🎉

**Comment by shirshak55** [comment]
wow  :)
