### ISSUE TITLE
Logout page not found

### ISSUE THREAD

**Issue by jbblesch** [gumbo-millennium/website#92]
When you log off, the site sends you to a page that doens't excist:
https://www.gumbo-millennium.nl/auth/logout

**Comment by roelofr** [comment]
Nah, the logout page is only available using `POST`, since the logout route is a non-idempotent route (it changes the session). It also prevents the browser from preloading it ([source][1]) and ensures it's never cached (`POST`-requests shouldn't be cached).

[1]: https://stackoverflow.com/a/14587231
